/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.updatewatch;

import controller.MeterDAO;
import controller.UserDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Meter;
import model.User;

/**
 *
 * @author HP
 */
public class UpdateMain extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMain
     */
    private DefaultTableModel model;

    public UpdateMain() {
        initComponents();
        setTitle("Cập nhật số nước");
        setSize(830, 450);
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.white);
        meterTable.setBackground(Color.white);
        fillTable();
    }

    private void fillTable() {
        model = (DefaultTableModel) meterTable.getModel();
        model.setRowCount(0);
        MeterDAO meterDAO = new MeterDAO();
        List<Meter> list = meterDAO.getAllMeter();
        UserDAO userDAO = new UserDAO();
        for (Meter meter : list) {
            User user = userDAO.getUserById(meter.getCustomer_id());
            model.addRow(new Object[]{user.getAccount_code(), user.getName(), user.getAddress(),
            meter.getSerial_number(), meter.getMeter_id(), user.getUser_id()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameKH = new javax.swing.JTextField();
        findCustomerBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        meterTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Cập nhật số nước");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên khách hàng");

        nameKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        findCustomerBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findCustomerBTN.setText("Tìm kiếm");
        findCustomerBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findCustomerBTNMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        meterTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        meterTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        meterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Địa chỉ", "Mã công tơ", "id", "customer_id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        meterTable.setRowHeight(30);
        meterTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                meterTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        meterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(meterTable);
        if (meterTable.getColumnModel().getColumnCount() > 0) {
            meterTable.getColumnModel().getColumn(4).setMinWidth(0);
            meterTable.getColumnModel().getColumn(4).setPreferredWidth(0);
            meterTable.getColumnModel().getColumn(4).setMaxWidth(0);
            meterTable.getColumnModel().getColumn(5).setMinWidth(0);
            meterTable.getColumnModel().getColumn(5).setPreferredWidth(0);
            meterTable.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameKH, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addComponent(findCustomerBTN)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findCustomerBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // tìm kiếm khách hàng
    private void findCustomerBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findCustomerBTNMouseClicked
        String text = nameKH.getText();
        if (text.isEmpty()) {
            fillTable();
        } else {
            model = (DefaultTableModel) meterTable.getModel();
            model.setRowCount(0);
            MeterDAO meterDAO = new MeterDAO();
            List<Meter> list = meterDAO.getAllMeter();
            UserDAO udao = new UserDAO();
            for (Meter meter : list) {
                User user = udao.getUserById(meter.getCustomer_id());
                if (user.getName().toLowerCase().trim().matches(".*" + text.toLowerCase() + ".*")) {
                    model.addRow(new Object[]{user.getAccount_code(), user.getName(),
                        user.getAddress(), meter.getSerial_number(), meter.getMeter_id(), user.getUser_id()});
                }
            }
        }
    }//GEN-LAST:event_findCustomerBTNMouseClicked

    private void meterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterTableMouseClicked
        int row = meterTable.getSelectedRow();
        model = (DefaultTableModel) meterTable.getModel();
        int customer_id = (int) model.getValueAt(row, 5);
        int meter_id = (int) model.getValueAt(row, 4);
        new UpdateDetail(meter_id, customer_id).setVisible(true);
        dispose();
    }//GEN-LAST:event_meterTableMouseClicked

    private void meterTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_meterTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_meterTableAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findCustomerBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable meterTable;
    private javax.swing.JTextField nameKH;
    // End of variables declaration//GEN-END:variables
}
