/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.updateWater;

import controller.MeterDAO;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Meter;

/**
 *
 * @author HP
 */
public class UpdateMain extends javax.swing.JFrame {

    /**
     * Creates new form UpdateMain
     */
    private DefaultTableModel model;

    public UpdateMain() {
        initComponents();
        setTitle("Cập nhật số nước");
        setLocationRelativeTo(this);
        getContentPane().setBackground(Color.white);
        meterTable.setBackground(Color.white);
        fillTable();
    }

    private void fillTable() {
        model = (DefaultTableModel) meterTable.getModel();
        model.setRowCount(0);
        MeterDAO meterDAO = new MeterDAO();
        List<Meter> list = meterDAO.getAllMeter();
        for (Meter meter : list) {
            model.addRow(new Object[]{meter.getUser().getAccount_code(), meter.getUser().getName(),
                meter.getUser().getAddress(), meter.getSerial_number(), meter.getMeter_id()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameKH = new javax.swing.JTextField();
        findCustomerBTN = new javax.swing.JButton();
        updateAllBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        meterTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Cập nhật số nước");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Họ tên khách hàng");

        nameKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        findCustomerBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        findCustomerBTN.setText("Tìm kiếm");
        findCustomerBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findCustomerBTNMouseClicked(evt);
            }
        });

        updateAllBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateAllBTN.setText("Cập nhật toàn bộ");
        updateAllBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateAllBTNMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        meterTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        meterTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        meterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Họ tên", "Địa chỉ", "Mã công tơ", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        meterTable.setRowHeight(30);
        meterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(meterTable);
        if (meterTable.getColumnModel().getColumnCount() > 0) {
            meterTable.getColumnModel().getColumn(4).setMinWidth(0);
            meterTable.getColumnModel().getColumn(4).setPreferredWidth(0);
            meterTable.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(nameKH, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(findCustomerBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(updateAllBTN)
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findCustomerBTN)
                    .addComponent(updateAllBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // tìm kiếm khách hàng
    private void findCustomerBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findCustomerBTNMouseClicked
        String text = nameKH.getText();
        if (text.isEmpty()) {
            fillTable();
        } else {
            model = (DefaultTableModel) meterTable.getModel();
            model.setRowCount(0);
            MeterDAO meterDAO = new MeterDAO();
            List<Meter> list = meterDAO.getAllMeter();
            for (Meter meter : list) {
                if (meter.getUser().getName().toLowerCase().trim().matches(".*" + text.toLowerCase() + ".*")) {
                    model.addRow(new Object[]{meter.getUser().getAccount_code(), meter.getUser().getName(),
                        meter.getUser().getAddress(), meter.getSerial_number(), meter.getMeter_id()});
                }
            }
        }
    }//GEN-LAST:event_findCustomerBTNMouseClicked

    private void meterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meterTableMouseClicked
        int row = meterTable.getSelectedRow();
        model = (DefaultTableModel) meterTable.getModel();
        int meter_id = (int) model.getValueAt(row, 4);
        String meter_seri = (String)model.getValueAt(row, 3);
        new UpdateDetail(meter_id, meter_seri).setVisible(true);
        dispose();
    }//GEN-LAST:event_meterTableMouseClicked

    private void updateAllBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateAllBTNMouseClicked
        new UpdateAll().setVisible(true);
        dispose();
    }//GEN-LAST:event_updateAllBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMain.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findCustomerBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable meterTable;
    private javax.swing.JTextField nameKH;
    private javax.swing.JButton updateAllBTN;
    // End of variables declaration//GEN-END:variables
}
